---

- name: Setup nscd daemon
  ansible.builtin.include_role:
    name: amtega.packages
  vars:
    packages_os:
      all:
        all:
          nscd: present
  tags:
    - role::nscd
    - role::nscd::install
