---
# Role tasks

- block:
    - include_tasks: install.yml
      when: nscd_state == "present"
      tags:
        - role::nscd::install

    - include_tasks: configure.yml
      when: nscd_state == "present"
      tags:
        - role::nscd::configure

    - include_tasks: service.yml
      when: nscd_state == "present"
      tags:
        - role::nscd::service

    - name: Remove nscd
      include_tasks: uninstall.yml
      when: nscd_state == 'absent'
      tags:
        - role::nscd::uninstall
  tags:
    - role::nscd
