---

- name: Setup nscd
  block:
    - name: Manage nscd present state
      block:
        - ansible.builtin.include_tasks: install.yml
          tags:
            - role::nscd::install

        - ansible.builtin.include_tasks: configure.yml
          tags:
            - role::nscd::configure
      when: nscd_state == "present"

    - name: Manage nscd absent state
      ansible.builtin.include_tasks: uninstall.yml
      when: nscd_state == "absent"
      tags:
        - role::nscd::uninstall
  tags:
    - role::nscd
