---

- name: "stop service"
  service:
    name: nscd
    enabled: no
    state: stopped

- name: "remove nscd"
  include_role:
    name: amtega.packages
  vars:
    packages_os:
      all:
        all:
          nscd: absent
