---

- name: Uninstall nscd
  block:
    - name: Stop nscd service
      ansible.builtin.service:
        name: "{{ nscd_service_name }}"
        enabled: no
        state: stopped

    - name: Remove ncsd daemon
      ansible.builtin.include_role:
        name: amtega.packages
      vars:
        packages_os:
          all:
            all:
              nscd: absent
  tags:
    - role::nscd
    - role::nscd::uninstall
