---
# Uninstall tasks

- block:
    - name: Stop nscd service
      service:
        name: "{{ nscd_service_name }}"
        enabled: no
        state: stopped

    - name: Remove ncsd daemon
      include_role:
        name: amtega.packages
      vars:
        packages_os:
          all:
            all:
              nscd: absent
  tags:
    - role::nscd
    - role::nscd::uninstall
